vehicle_info:
  wheel_base_m: 3.0
  vehicle_width_m: 1.85
  vehicle_length_m: 4.85
  axle_to_front_bumper_m: 3.90
  axle_to_rear_bumper_m: 0.95

planning:
  desired_speed: 11.11  # 40 km/h
  log_level: "info"     # options: trace, debug, info, warn, err, critical, off
  mppi_params:
    lambda: 1.5
    noise_sigma:
      jerk_std: 0.5
      steer_rate_std: 0.02
    num_samples: 16384   # options: 1024, 2048, 4096, 8192, 16384
  cost_weights:
    position_weight: 50.0
    velocity_weight: 5
    heading_weight: 1000.0
    accel_effort_weight: 10.0
    steer_effort_weight: 80.0
    jerk_effort_weight: 20.0
    steer_rate_effort_weight: 120.0
  constraint_limits:
    max_accel_mps2: 2.0
    min_accel_mps2: -4.0
    min_jerk_mps3: -1.5
    max_jerk_mps3: 1.5
    max_steer_rate_rps: 0.10
    max_steer_angle_rad: 0.35
    longitudinal_safety_margin_m: 2.5
    lateral_safety_margin_m: 0.8

simulator:
  scenario_file_path: "scenarios/DEU_Schwetzingen-176_1_T-2.xml"
  planning_problem_id: 2066
  log_level: "info"
  perception_range_m: 120.0

visualization:
  save_mcap: true
  log_level: "info"
